# app/config/common/config_liip.yml
liip_imagine:
    resolvers:
       default:
          web_path:
              web_root:     %kernel.root_dir%/../www
              cache_prefix: thumbs/cache

    loaders:
       default:
          filesystem:
             data_root: %kernel.root_dir%/../www/

    filter_sets:
        cache: ~

        catalog_thumb_watermark:
            quality: 100
            filters:
                thumbnail: { size: [300, 200], mode: outbound }
                crop:      { start: [0, 0], size: [300, 200] }
                watermark:
                    image:    ../www/bundles/app/images/logo_watermark.png
                    size:     0.2
                    position: bottomright

        catalog_watermark:
            quality: 100
            filters:
                watermark:
                    image:    ../www/bundles/app/images/logo_watermark.png
                    size:     0.2
                    position: bottomright

        staff_thumb:
            quality: 100
            filters:
                thumbnail: { size: [420, 320], mode: outbound }

        article_thumb:
            quality: 100
            filters:
                thumbnail: { size: [600, 330], mode: outbound }

        research_category_thumb:
            quality: 100
            filters:
                thumbnail: { size: [600, 330], mode: outbound }

        information_thumb:
            quality: 100
            filters:
                thumbnail: { size: [200, 200], mode: inset }
                background: { size: [200, 200], color: '#fff' }
