# app/config/common/services.yml
services:
    #Twig

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.metadata_extension:
        class:  AppBundle\Twig\MetadataExtension
        calls:
             - [setRequestStack, [ "@request_stack" ]]
             - [setManager, [ "@doctrine.orm.entity_manager" ]]
        public: false
        tags:
            - { name: twig.extension }

    app.roman_number_extension:
        class:  AppBundle\Twig\RomanNumberExtension
        public: false
        tags:
            - { name: twig.extension }

    # Event listeners

    app.listener.fallback.ie:
        class: AppBundle\EventListener\Fallback\IeFallbackListener
        calls:
            - [setIeFallbackController, [ "@app.ie_fallback_controller" ]]
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
            - [setCurrencyConverter, [ "@app.currency_converter" ]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Controller

    app.ie_fallback_controller:
        class: AppBundle\Controller\Fallback\IeFallbackController
        calls:
            - [setTemplating, [ "@templating" ]]

    # Constraints

    app.constraint.is_type_residential_valid:
        class: AppBundle\Validator\Constraints\IsTypeResidentialValidConstraintValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: is_type_residential_valid }

    app.constraint.is_type_commercial_valid:
        class: AppBundle\Validator\Constraints\IsTypeCommercialValidConstraintValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: is_type_commercial_valid }

    app.constraint.is_trade_type_valid:
        class: AppBundle\Validator\Constraints\IsTradeTypeValidConstraintValidator
        tags:
            - { name: validator.constraint_validator, alias: is_trade_type_valid }

    app.constraint.is_layout_type_valid:
        class: AppBundle\Validator\Constraints\IsLayoutTypeValidConstraintValidator
        tags:
            - { name: validator.constraint_validator, alias: is_layout_type_valid }

    app.constraint.is_fit_out_type_valid:
        class: AppBundle\Validator\Constraints\IsFitOutTypeValidConstraintValidator
        tags:
            - { name: validator.constraint_validator, alias: is_fit_out_type_valid }

    # Services

    app.backlink:
        class: AppBundle\Service\Backlink
        arguments:
            - "@session"

    app.mailer_shortcut:
        class: AppBundle\Service\MailerShortcut
        arguments:
            - "@mailer"

    app.geo_coder:
        class: AppBundle\Service\GeoCoder

    app.pagination_bar:
        class: AppBundle\Service\PaginationBar

    app.currency_converter:
        class: AppBundle\Service\CurrencyConverter

    app.filter.available_values_extractor:
        class: AppBundle\Service\Filter\AvailableValuesExtractor

    app.filter.validator:
        class: AppBundle\Service\Filter\Validator
        calls:
            - [setAvailableValuesExtractor, ["@app.filter.available_values_extractor"]]

    app.filter.utility.currency:
        class: AppBundle\Service\Filter\Utility\Currency
        calls:
            - [setSession, ["@session"]]
