# app/config/common/services.yml
services:
    #Twig

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.metadata_extension:
        class:  AppBundle\Twig\MetadataExtension
        calls:
             - [setRequestStack, [ "@request_stack" ]]
             - [setManager, [ "@doctrine.orm.entity_manager" ]]
        public: false
        tags:
            - { name: twig.extension }

    app.roman_number_extension:
        class:  AppBundle\Twig\RomanNumberExtension
        public: false
        tags:
            - { name: twig.extension }

    # Constraints

    app.constraint.is_type_valid:
        class: AppBundle\Validator\Constraints\IsTypeValidConstraintValidator
        arguments:
            - "@doctrine.orm.entity_manager"

    # Services

    app.backlink:
        class: AppBundle\Service\Backlink
        arguments:
            - "@session"

    app.mailer_shortcut:
        class: AppBundle\Service\MailerShortcut
        arguments:
            - "@mailer"

    app.geo_coder:
        class: AppBundle\Service\GeoCoder

    app.filter.available_values_extractor:
        class: AppBundle\Service\Filter\AvailableValuesExtractor

    app.filter.validator:
        class: AppBundle\Service\Filter\Validator
        calls:
            - [setAvailableValuesExtractor, ["@app.filter.available_values_extractor"]]